export const FETCHING_PEOPLE_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_PEOPLE_REQUEST_suces = 'FETCHING_PEOPLE_REQUEST_suces';
export const FETCHING_PEOPLE_REQUEST_eror = 'FETCHING_PEOPLE_REQUEST_eror';

export const TT = 'TT';
